port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.2/dns-query
    - https://1.0.0.2/dns-query
    - https://9.9.9.9/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
proxies:
  # shadowsocks
  # 支持加密方式：
  #   aes-128-gcm aes-192-gcm aes-256-gcm
  #   aes-128-cfb aes-192-cfb aes-256-cfb
  #   aes-128-ctr aes-192-ctr aes-256-ctr
  #   rc4-md5 chacha20 chacha20-ietf xchacha20
  #   chacha20-ietf-poly1305 xchacha20-ietf-poly1305

  - name: "ss1"
    type: ss
    server: server
    port: 443
    cipher: chacha20-ietf-poly1305
    password: "password"
    # udp: true

  - name: "ss2"
    type: ss
    server: server
    port: 443
    cipher: AEAD_CHACHA20_POLY1305
    password: "password"
    plugin: obfs
    plugin-opts:
      mode: tls # 混淆模式，可以选择 http 或 tls
      host: bing.com # 混淆域名，需要和服务器配置保持一致

  - name: "ss3"
    type: ss
    server: server
    port: 443
    cipher: AEAD_CHACHA20_POLY1305
    password: "password"
    plugin: v2ray-plugin
    plugin-opts:
      mode: websocket # 暂时不支持 QUIC 协议
      # tls: true # wss
      # skip-cert-verify: true
      # host: bing.com
      # path: "/"
      # headers:
      #   custom: value

  # vmess
  # 支持加密方式：auto / aes-128-gcm / chacha20-poly1305 / none
  - name: "vmess"
    type: vmess
    server: server
    port: 443
    uuid: uuid
    alterId: 32
    cipher: auto
    # udp: true
    # tls: true
    # skip-cert-verify: true
    # servername: example.com # 优先级高于 wss host
    # network: ws
    # ws-path: /path
    # ws-headers:
    #   Host: v2ray.com

  - name: "vmess-http"
    type: vmess
    server: server
    port: 443
    uuid: uuid
    alterId: 32
    cipher: auto
    # udp: true
    # network: http
    # http-opts:
    #   # method: "GET"
    #   # path:
    #   #   - '/'
    #   #   - '/video'
    #   # headers:
    #   #   Connection:
    #   #     - keep-alive

  # socks5
  - name: "socks"
    type: socks5
    server: server
    port: 443
    # username: username
    # password: password
    # tls: true
    # skip-cert-verify: true
    # udp: true

  # http
  - name: "http"
    type: http
    server: server
    port: 443
    # username: username
    # password: password
    # tls: true # https
    # skip-cert-verify: true

  # snell (注意：暂时不支持 UDP 转发)
  - name: "snell"
    type: snell
    server: server
    port: 44046
    psk: yourpsk
    # obfs-opts:
    # mode: http # 或 tls
    # host: bing.com

  # Trojan
  - name: "trojan"
    type: trojan
    server: server
    port: 443
    password: yourpsk
    # udp: true
    # sni: example.com # 服务名称
    # alpn:
    #   - h2
    #   - http/1.1
    # skip-cert-verify: true

  # ShadowsocksR
  # 支持的加密方式: SS 中支持的所有流加密方式
  # 支持的混淆方式:
  #   plain http_simple http_post
  #   random_head tls1.2_ticket_auth tls1.2_ticket_fastauth
  # 支持的协议:
  #   origin auth_sha1_v4 auth_aes128_md5
  #   auth_aes128_sha1 auth_chain_a auth_chain_b
  - name: "ssr"
    type: ssr
    server: server
    port: 443
    cipher: chacha20-ietf
    password: "password"
    obfs: tls1.2_ticket_auth
    protocol: auth_sha1_v4
    # obfs-param: domain.tld
    # protocol-param: "#"
    # udp: true

proxy-groups:

  - name: Auto
    type: url-test
    proxies:
      - ss1
      - ss2
      - trojan
      - ssr
    # tolerance: 150
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

rule-providers:

  reject:
    type: file
    behavior: domain
    path: ./ruleset/reject.yaml

  icloud:
    type: file
    behavior: domain
    path: ./ruleset/icloud.yaml

  apple:
    type: file
    behavior: domain
    path: ./ruleset/apple.yaml
    

  google:
    type: file
    behavior: domain
    path: ./ruleset/google.yaml

  proxy:
    type: file
    behavior: domain
    path: ./ruleset/proxy.yaml
    

  direct:
    type: file
    behavior: domain
    path: ./ruleset/direct.yaml
    

  private:
    type: file
    behavior: domain
    path: ./ruleset/private.yaml
    
  gfw:
    type: file
    behavior: domain
    path: ./ruleset/gfw.yaml

  tld-not-cn:
    type: file
    behavior: domain
    path: ./ruleset/tld-not-cn.yaml
  
  telegramcidr:
    type: file
    behavior: ipcidr
    path: ./ruleset/telegramcidr.yaml

  cncidr:
    type: file
    behavior: ipcidr
    path: ./ruleset/cncidr.yaml

  lancidr:
    type: file
    behavior: ipcidr
    path: ./ruleset/lancidr.yaml

  applications:
    type: file
    behavior: classical
    path: ./ruleset/applications.yaml

  chatGPT:
    type: file
    behavior: domain
    path: ./ruleset/chatGPT.yaml

  engineer:
    type: file
    behavior: domain
    path: ./ruleset/engineer.yaml
    
rules:
  - RULE-SET,applications,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,chatGPT,Auto
  - RULE-SET,engineer,Auto  
  - RULE-SET,google,Auto
  - RULE-SET,gfw,Auto
  - RULE-SET,proxy,Auto
  - RULE-SET,tld-not-cn,Auto
  - RULE-SET,telegramcidr,Auto
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Auto